version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 219315770087.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker-compose build auth
      - docker tag reservation-auth 219315770087.dkr.ecr.us-east-1.amazonaws.com/auth


      - docker-compose build reservations
      - docker tag reservation-reservations 219315770087.dkr.ecr.us-east-1.amazonaws.com/reservations


      - docker-compose build payments
      - docker tag reservation-payments 219315770087.dkr.ecr.us-east-1.amazonaws.com/payments

      - docker-compose build notifications
      - docker tag reservation-notifications 219315770087.dkr.ecr.us-east-1.amazonaws.com/notifications
  post_build:
    commands:
      - docker push 219315770087.dkr.ecr.us-east-1.amazonaws.com/auth
      - docker push 219315770087.dkr.ecr.us-east-1.amazonaws.com/reservations
      
      - docker push 219315770087.dkr.ecr.us-east-1.amazonaws.com/payments
      - docker push 219315770087.dkr.ecr.us-east-1.amazonaws.com/notifications