services:
  auth: 
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - 3001:3001
  reservations: 
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
    command: npm run start:dev reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - 3000:3000
  payments: 
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
    command: npm run start:dev payments
    env_file:
      - ./apps/payments/.env
    ports:
      - 3003:3003
  mongo:
    image: mongo
    
  
