services:
  auth: 
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    image: auth
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - 3001:3001
  reservations: 
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    image: reservations
    command: npm run start:dev reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - 3000:3000
  payments: 
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    image: payments
    command: npm run start:dev payments
    env_file:
      - ./apps/payments/.env
  notifications: 
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    image: notifications
    command: npm run start:dev notifications
    env_file:
      - ./apps/notifications/.env
  mongo:
    image: mongo
    
  
