services:
  auth: 
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    command: npm run start:dev auth
    ports:
      - 3001:3001
  reservations: 
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
    command: npm run start:dev reservations
    ports:
      - 3000:3000
  mongo:
    image: mongo
    
  
