FROM node:18 As development

# Create app directory
WORKDIR /usr/src/app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./


RUN npm install

COPY . .

RUN npm run build notifications

CMD ["node", "dist/apps/notifications/main"]