FROM node:18

# Create app directory
WORKDIR /usr/src/app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./


RUN npm install

COPY . .

RUN npm run build payments

CMD ["node", "dist/apps/payments/main"]